name: PR Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  java-spotless:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Run Spotless Check
      run: |
        cd java
        ./gradlew spotlessCheck

  java-samples-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [otlpmetric, otlptrace, resource, otlp-spring, otlpmetrics-function, autoconf-auth-extension]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build Sample
      run: |
        cd java/${{ matrix.sample }}
        ../gradlew build

  go-samples-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [metric/otlpgrpc, trace/otlpgrpc, trace/otlphttp]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.3'
    - name: Build Go Sample
      run: |
        cd golang/${{ matrix.sample }}
        go build -v ./...

  go-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [metric/otlpgrpc, trace/otlpgrpc, trace/otlphttp]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.3'
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: |
          cd golang/${{ matrix.sample }}
          $(go env GOPATH)/bin/golangci-lint run

  python-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [otlpmetric]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd python/${{ matrix.sample }}
        pip install -r requirements.txt
        pip install flake8
    - name: Run flake8
      run: |
        cd python/${{ matrix.sample }}
        flake8 .

  python-samples-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sample: [otlpmetric]
        py-version: ['3.10', '3.11', '3.12', '3.13']
    name: Build Python ${{ matrix.py-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.py-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}
    - name: Install dependencies
      run: |
        cd python/${{ matrix.sample }}
        pip install -r requirements.txt
    - name: Verify build (Syntax check)
      run: |
        cd python/${{ matrix.sample }}
        python -m py_compile *.py
